# 2. Write programs in Python using NumPy library to do the following:

In [3]:
import numpy as np

## a. Compute the mean, standard deviation, and variance of a two dimensional random integer array along the second axis.

In [4]:
arr = np.random.randint(1,50,(4,6))
arr

array([[ 8,  8, 49, 11, 34, 13],
       [30, 30, 21, 10, 39, 30],
       [ 7,  4, 37, 45, 20, 20],
       [29, 25, 25, 26, 21,  7]])

In [5]:
#Mean
print('Mean: ',arr.mean(axis=1))
#standard deviation
print('Standard Deviation: ',arr.std(axis=1))
#variance
print('Variance: ',arr.var(axis=1))

Mean:  [20.5        26.66666667 22.16666667 22.16666667]
Standard Deviation:  [15.56438242  9.08600878 14.78080587  7.17441442]
Variance:  [242.25        82.55555556 218.47222222  51.47222222]


## b. Get the indices of the sorted elements of a given array. 
## B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]

In [6]:
B = [56, 48, 22, 41, 78, 91, 24, 46, 8, 33]
arr1 = np.array(B)
print("Sorted array: ",np.sort(arr1))
print("Indices of the sorted elements of a given array: ",np.argsort(arr1))

Sorted array:  [ 8 22 24 33 41 46 48 56 78 91]
Indices of the sorted elements of a given array:  [8 2 6 9 3 7 1 0 4 5]


## c. Create a 2-dimensional array of size m x n integer elements, also print the shape, type and datatype of the array and then reshape it into nx m array, n and m are user inputs given at the run time.

In [7]:
m = int(input('Enter the number of rows: '))
n = int(input('Enter the number of columns: '))
arr2 = np.random.randint(1,100,(m,n))
print(arr2)
print('Shape: ',arr2.shape)
print('Type: ',type(arr2))
print('Data Type: ',arr2.dtype)
arr2 = arr2.reshape(n,m)
print('After reshaping: \n',arr2)
print('New Shape: ',arr2.shape)

Enter the number of rows: 3
Enter the number of columns: 4
[[ 8 58 71 67]
 [11 36 33 93]
 [12  4 28 37]]
Shape:  (3, 4)
Type:  <class 'numpy.ndarray'>
Data Type:  int32
After reshaping: 
 [[ 8 58 71]
 [67 11 36]
 [33 93 12]
 [ 4 28 37]]
New Shape:  (4, 3)


## d. Test whether the elements of a given array are zero, non-zero and NaN. Record the indices of these elements in three separate arrays.

In [8]:
x = np.array([1, 0, 3, 4, 0, 0, 3, 2, 1, np.nan, 3, np.nan])
print("THE ARRAY IS: ",x)

THE ARRAY IS:  [ 1.  0.  3.  4.  0.  0.  3.  2.  1. nan  3. nan]


In [9]:
print("\nTest whether elements of the array are zero : ", np.all(x))
res = np.where(x == 0)[0]
print("The indices of the  zero elements: ",res)


Test whether elements of the array are zero :  False
The indices of the  zero elements:  [1 4 5]


In [10]:
print("\nTest whether elements of the array are non-zero : ",np.any(x))
res = np.where(x != 0)[0]
print("The indices of the non- zero elements: ",res)


Test whether elements of the array are non-zero :  True
The indices of the non- zero elements:  [ 0  2  3  6  7  8  9 10 11]


In [11]:
print("\nTest whether elements of the array are NaN :: ",np.isnan(x))
res = np.where(np.isnan(x) == True)[0]
print("The indices of the NaN elements: ",res)


Test whether elements of the array are NaN ::  [False False False False False False False False False  True False  True]
The indices of the NaN elements:  [ 9 11]
